"use client";

import Link from "next/link";
import { RecommendedForYou } from "../components/RecommendedForYou";
import { RecentlyViewed } from "../components/RecentlyViewed";

export default function HomePage() {
  return <main><section className="hero"><div className="container hero-grid"><div><span className="eyebrow-large">the open market for machine intelligence</span><h1>Buy better.<br /><em>Build openly.</em></h1><p className="hero-copy">NeuralBazaar connects the people building AI with the people putting it to work. Discover verified models, license them on-chain, and earn every time your work creates value.</p><div className="hero-actions"><Link href="/marketplace" className="button button-dark">Explore models <span className="ml-2">→</span></Link><Link href="/login" className="button button-soft">Start selling</Link></div><div className="mt-9 flex flex-wrap gap-6 text-xs font-semibold text-slate-500"><span>✦ 100% on-chain payments</span><span>✦ IPFS-backed assets</span><span>✦ creator royalties</span></div></div><div className="hero-visual"><div className="visual-panel"><div className="visual-top"><span>market pulse</span><span className="live-dot">● live on sepolia</span></div><div className="visual-value">1,284 <small>models</small></div><div className="visual-bars"><span /><span /><span /><span /><span /><span /><span /></div><div className="visual-bottom"><span>volume · last 30 days</span><span>+28.4%</span></div></div></div></div></section><RecommendedForYou /><RecentlyViewed /><section className="section pt-5"><div className="container"><div className="rounded-[28px] bg-ink p-8 text-white md:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="eyebrow !text-mint">for builders with a point of view</p><h2 className="mt-3 max-w-xl text-4xl font-extrabold leading-none tracking-[-.07em] md:text-5xl">Your model should earn beyond the first sale.</h2><p className="mt-5 max-w-xl leading-7 text-white/60">Publish once, set a royalty, and let transparent smart contracts keep your upside attached to the work.</p></div><Link href="/creator" className="button button-coral">Publish a model →</Link></div></div></div></section></main>;
}
