"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Model, ModelCard } from "../components/ModelCard";
import { apiFetch } from "../lib/api";

const fallbackModels: Model[] = [
  { id: "sample-1", model_id_onchain: 1001, creator_wallet: "0x1111111111111111111111111111111111111111", creator_name: "VectorForge", title: "Vector Vision Pro", description: "High-accuracy image embeddings for product search and visual discovery.", category: "Computer Vision", tags: ["embeddings"], license: "Apache-2.0", rating: 4.9 },
  { id: "sample-2", model_id_onchain: 1002, creator_wallet: "0x2222222222222222222222222222222222222222", creator_name: "SignalWorks", title: "Signal Forecast 2.1", description: "Interpretable forecasting for operational demand and capacity planning.", category: "Forecasting", tags: ["forecasting"], license: "MIT", rating: 4.7 },
  { id: "sample-3", model_id_onchain: 1003, creator_wallet: "0x3333333333333333333333333333333333333333", creator_name: "SmallWorld Labs", title: "Mosaic Classifier", description: "A compact classifier tuned for edge deployments and low-latency inference.", category: "Edge AI", tags: ["edge"], license: "MIT", rating: 4.8 }
];

export default function HomePage() {
  const [models, setModels] = useState<Model[]>(fallbackModels);
  useEffect(() => { apiFetch<{ models: Model[] }>("/api/models").then(data => { if (data.models.length) setModels(data.models.slice(0, 3)); }).catch(() => undefined); }, []);
  return <main><section className="hero"><div className="container hero-grid"><div><span className="eyebrow-large">the open market for machine intelligence</span><h1>Buy better.<br /><em>Build openly.</em></h1><p className="hero-copy">NeuralBazaar connects the people building AI with the people putting it to work. Discover verified models, license them on-chain, and earn every time your work creates value.</p><div className="hero-actions"><Link href="/marketplace" className="button button-dark">Explore models <span className="ml-2">↗</span></Link><Link href="/login" className="button button-soft">Start selling</Link></div><div className="mt-9 flex flex-wrap gap-6 text-xs font-semibold text-slate-500"><span>✦ 100% on-chain payments</span><span>✦ IPFS-backed assets</span><span>✦ creator royalties</span></div></div><div className="hero-visual"><div className="visual-panel"><div className="visual-top"><span>market pulse</span><span className="live-dot">● live on sepolia</span></div><div className="visual-value">1,284 <small>models</small></div><div className="visual-bars"><span /><span /><span /><span /><span /><span /><span /></div><div className="visual-bottom"><span>volume · last 30 days</span><span>+28.4%</span></div></div></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">curated intelligence</p><h2>Models worth<br />putting to work.</h2></div><p>Every listing carries its creator, license, provenance, and reputation with it. Find the right building block for your next product.</p></div><div className="grid-cards">{models.map(model => <ModelCard key={model.id} model={model} />)}</div><div className="mt-7 text-center"><Link href="/marketplace" className="button button-soft">View the full marketplace →</Link></div></div></section><section className="section pt-5"><div className="container"><div className="rounded-[28px] bg-ink p-8 text-white md:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="eyebrow !text-mint">for builders with a point of view</p><h2 className="mt-3 max-w-xl text-4xl font-extrabold leading-none tracking-[-.07em] md:text-5xl">Your model should earn beyond the first sale.</h2><p className="mt-5 max-w-xl leading-7 text-white/60">Publish once, set a royalty, and let transparent smart contracts keep your upside attached to the work.</p></div><Link href="/creator" className="button button-coral">Publish a model →</Link></div></div></div></section></main>;
}
