"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch } from "../lib/api";

type Period = "weekly" | "monthly" | "all-time";
type BoardItem = { id: string; label: string; username?: string; avatar_url?: string | null; title?: string; category?: string; model_id_onchain?: number; models?: number; sales?: number; downloads?: number; rating?: number | string; purchases?: number; bookmarks?: number; likes?: number; shares?: number; views?: number };
type Boards = { creators: BoardItem[]; customers: BoardItem[]; models: BoardItem[]; datasets: BoardItem[]; prompts: BoardItem[]; agents: BoardItem[] };

function Leaderboard({ title, eyebrow, items, modelLinks = false }: { title: string; eyebrow: string; items: BoardItem[]; modelLinks?: boolean }) {
  return <section className="panel community-leaderboard"><div className="dashboard-section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><span className="leaderboard-crown">TOP 10</span></div>{items.length ? <div className="leaderboard-list">{items.map((item, index) => <div className="leaderboard-row" key={item.id}><span className="leaderboard-rank">{String(index + 1).padStart(2, "0")}</span><div className="leaderboard-avatar">{item.avatar_url ? <img src={item.avatar_url} alt="" /> : (item.label || "N").slice(0, 1).toUpperCase()}</div><div className="leaderboard-label">{modelLinks ? <Link href={`/marketplace/${item.id}`}><strong>{item.label}</strong></Link> : <strong>{item.label}</strong>}<span>{item.category || (item.username ? `@${item.username}` : "Community member")}</span></div><div className="leaderboard-score"><strong>{modelLinks ? `${Number(item.likes || 0) + Number(item.sales || 0)} activity` : item.sales != null ? `${item.sales} sales` : item.purchases != null ? `${item.purchases} purchases` : `${item.models || item.downloads || 0} points`}</strong><span>{item.rating ? `★ ${Number(item.rating).toFixed(1)}` : `${Number(item.downloads || item.views || item.bookmarks || 0).toLocaleString()} signals`}</span></div>{modelLinks ? <Link className="leaderboard-open" href={`/marketplace/${item.id}/discussion`}>Discuss</Link> : null}</div>)}</div> : <div className="empty-state">No activity in this period yet.</div>}</section>;
}

export default function CommunityHub() {
  const [period, setPeriod] = useState<Period>("weekly"); const [boards, setBoards] = useState<Boards | null>(null); const [error, setError] = useState("");
  useEffect(() => { setError(""); apiFetch<{ leaderboards: Boards }>(`/api/community/leaderboards?period=${period}`).then(result => setBoards(result.leaderboards)).catch(value => setError(value instanceof Error ? value.message : "Could not load leaderboards")); }, [period]);
  return <main className="page-shell"><div className="container"><div className="page-heading"><p className="eyebrow">community · like GitHub meets Product Hunt</p><h1>Build in public.<br />Find your people.</h1><p>Review, discuss, bookmark, share, and follow the AI work that deserves attention.</p></div><div className="community-periods" role="tablist" aria-label="Leaderboard period"><span className="control-label">Rankings</span>{(["weekly", "monthly", "all-time"] as Period[]).map(value => <button key={value} className={period === value ? "community-period community-period-active" : "community-period"} onClick={() => setPeriod(value)}>{value === "all-time" ? "All time" : value[0].toUpperCase() + value.slice(1)}</button>)}</div>{error ? <div className="notice-error mb-5">{error}</div> : null}{!boards ? <div className="empty-state">Loading community rankings...</div> : <div className="community-grid"><Leaderboard title="Top creators" eyebrow="people who ship" items={boards.creators} /><Leaderboard title="Top customers" eyebrow="people who build" items={boards.customers} /><Leaderboard title="Top models" eyebrow="most loved AI" items={boards.models} modelLinks /><Leaderboard title="Top datasets" eyebrow="data that compounds" items={boards.datasets} modelLinks /><Leaderboard title="Top prompts" eyebrow="reusable thinking" items={boards.prompts} modelLinks /><Leaderboard title="Top agents" eyebrow="systems in motion" items={boards.agents} modelLinks /></div>}</div></main>;
}
