"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useAuth } from "./AuthProvider";
import { apiFetch } from "../lib/api";

type Discussion = { id: string; kind: "discussion" | "bug" | "feature" | "question"; title: string; body: string; status: string; author_username?: string; author_display_name?: string; author_avatar?: string | null; comment_count: number; created_at: string };
type CommunityData = { model: { id: string; title: string; description: string; category: string }; stats: { likes: number; bookmarks: number; shares: number; discussions: number }; discussions: Discussion[] };

export default function ModelCommunity({ modelId }: { modelId: string }) {
  const { user, connectWallet } = useAuth(); const [data, setData] = useState<CommunityData | null>(null); const [message, setMessage] = useState(""); const [liked, setLiked] = useState(false); const [busy, setBusy] = useState(false);
  async function load() { try { const result = await apiFetch<CommunityData>(`/api/community/models/${modelId}/community`); setData(result); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load community"); } }
  useEffect(() => { void load(); }, [modelId]);
  async function requireUser() { if (user) return true; await connectWallet(); return false; }
  async function like() { if (!(await requireUser())) return; try { if (liked) { await apiFetch(`/api/community/models/${modelId}/like`, { method: "DELETE" }); setLiked(false); } else { await apiFetch(`/api/community/models/${modelId}/like`, { method: "POST" }); setLiked(true); } await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update like"); } }
  async function bookmark() { if (!(await requireUser())) return; try { await apiFetch(`/api/wishlist/${modelId}`, { method: "POST" }); setMessage("Bookmarked for later."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not bookmark model"); } }
  async function share() { try { const url = window.location.href; const nativeShare = "share" in navigator; if (nativeShare) await (navigator as Navigator & { share: (shareData: ShareData) => Promise<void> }).share({ title: data?.model.title, text: `Check out ${data?.model.title} on NeuralBazaar`, url }); else await navigator.clipboard.writeText(url); if (user) await apiFetch(`/api/community/models/${modelId}/share`, { method: "POST", body: JSON.stringify({ channel: nativeShare ? "native" : "copy_link" }) }); setMessage(nativeShare ? "Shared." : "Link copied."); await load(); } catch { setMessage("Share cancelled."); } }
  async function createDiscussion(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!(await requireUser())) return; setBusy(true); const form = new FormData(event.currentTarget); try { await apiFetch(`/api/community/models/${modelId}/discussions`, { method: "POST", body: JSON.stringify({ kind: String(form.get("kind")), title: String(form.get("title")), body: String(form.get("body")) }) }); event.currentTarget.reset(); setMessage("Discussion posted."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not post discussion"); } finally { setBusy(false); } }
  if (!data) return <div className="empty-state">Loading community...</div>;
  return <div className="model-community"><div className="community-action-row"><div><p className="eyebrow">model community</p><h2>Talk about {data.model.title}.</h2><p className="mt-2 text-sm text-slate-500">Ask questions, report bugs, request features, and help other builders evaluate the model.</p></div><div className="community-actions"><button className={liked ? "community-action community-action-active" : "community-action"} onClick={() => void like()}>♥ {data.stats.likes} Like</button><button className="community-action" onClick={() => void bookmark()}>🔖 {data.stats.bookmarks} Bookmark</button><button className="community-action" onClick={() => void share()}>↗ {data.stats.shares} Share</button></div></div><div className="community-stats"><span>{data.stats.discussions} discussions</span><span>{data.stats.likes} likes</span><span>{data.stats.bookmarks} bookmarks</span><span>{data.stats.shares} shares</span></div><div className="community-discussion-layout"><section className="panel"><div className="dashboard-section-heading"><div><p className="eyebrow">open threads</p><h2>Discussions</h2></div><Link href={`/marketplace/${modelId}`} className="button button-soft">Back to model</Link></div>{data.discussions.length ? <div className="discussion-list">{data.discussions.map(thread => <Link className="discussion-row" href={`/marketplace/${modelId}/discussion/${thread.id}`} key={thread.id}><span className={`discussion-kind discussion-kind-${thread.kind}`}>{thread.kind}</span><div><strong>{thread.title}</strong><p>{thread.body}</p><small>by @{thread.author_username || "member"} · {thread.comment_count} replies · {thread.status}</small></div><b>›</b></Link>)}</div> : <div className="empty-state">Start the first discussion for this model.</div>}</section><section className="panel"><p className="eyebrow">start a thread</p><h2>Open a conversation.</h2><form className="form-grid mt-5" onSubmit={createDiscussion}><div className="field"><label>Type</label><select className="select" name="kind"><option value="discussion">Discussion</option><option value="bug">Bug report</option><option value="feature">Feature request</option><option value="question">Question</option></select></div><div className="field full"><label>Title</label><input className="input" name="title" required placeholder="What should the community know?" /></div><div className="field full"><label>Details</label><textarea className="input textarea" name="body" required placeholder="Share context, reproduction steps, or an idea..." /></div><div className="field full"><button className="button button-violet" disabled={busy}>{busy ? "Posting..." : user ? "Post discussion" : "Connect to post"}</button></div></form></section></div>{message ? <p className="notice-success">{message}</p> : null}</div>;
}
