"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useWriteContract } from "wagmi";
import { useAuth } from "../../components/AuthProvider";
import { apiFetch } from "../../lib/api";
import { CONTRACTS } from "../../lib/config";
import { marketplaceAbi } from "../../lib/abis";
import { isSuperAdmin, roleLabel } from "../../lib/identity";

type User = { id: string; wallet_address: string; role: string; username?: string | null; created_at: string };
type Report = { id: string; title: string; reason: string; status: string; created_at: string };
export default function AdminPage() {
  const { user, ready } = useAuth(); const { writeContractAsync } = useWriteContract(); const [users, setUsers] = useState<User[]>([]); const [reports, setReports] = useState<Report[]>([]); const [analytics, setAnalytics] = useState<{ users: number; activeModels: number; purchases: number; volumeWei: string } | null>(null); const [message, setMessage] = useState("");
  async function load() { try { const [userData, reportData, analyticsData] = await Promise.all([apiFetch<{ users: User[] }>("/api/admin/users"), apiFetch<{ reports: Report[] }>("/api/reports"), apiFetch<{ analytics: typeof analytics }>("/api/admin/analytics")]); setUsers(userData.users); setReports(reportData.reports); setAnalytics(analyticsData.analytics); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not load admin data"); } }
  useEffect(() => { if (isSuperAdmin(user?.role)) void load(); else { setUsers([]); setReports([]); setAnalytics(null); } }, [user]);
  async function changeRole(id: string, role: string) { await apiFetch(`/api/admin/users/${id}/role`, { method: "PATCH", body: JSON.stringify({ role }) }); await load(); }
  async function pause() { try { await writeContractAsync({ address: CONTRACTS.marketplace, abi: marketplaceAbi, functionName: "pauseMarketplace" }); setMessage("Marketplace paused on-chain."); } catch (e) { setMessage(e instanceof Error ? e.message : "Pause failed"); } }
  async function unpause() { try { await writeContractAsync({ address: CONTRACTS.marketplace, abi: marketplaceAbi, functionName: "unpauseMarketplace" }); setMessage("Marketplace unpaused on-chain."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unpause failed"); } }
  if (!ready) return <main className="login-wrap"><div className="login-card"><p className="eyebrow">secure admin area</p><h1>Checking your session.</h1><p>Verifying your wallet session and current admin permissions.</p></div></main>;
  if (!user) return <main className="login-wrap"><div className="login-card"><p className="eyebrow">secure admin area</p><h1>Admin sign-in required.</h1><p>Connect an approved administrator wallet to continue.</p><Link href="/admin/login" className="button button-dark mt-5 inline-flex">Go to admin login</Link></div></main>;
  if (!isSuperAdmin(user.role)) return <main className="login-wrap"><div className="login-card"><p className="eyebrow">access denied</p><h1>Administrator approval required.</h1><p>This wallet is authenticated, but it does not have the admin role. Contact an existing administrator.</p><Link href="/dashboard" className="button button-soft mt-5 inline-flex">Back to dashboard</Link></div></main>;
  return <main className="page-shell"><div className="container"><div className="page-heading"><p className="eyebrow">control room · {roleLabel(user.role)}</p><h1>Keep the market<br />worthy of trust.</h1><p>Manage roles, review reports, and use the emergency pause when the marketplace needs a circuit breaker.</p></div><div className="stat-grid"><div className="stat"><span>users</span><strong>{analytics?.users ?? "—"}</strong></div><div className="stat"><span>published models</span><strong>{analytics?.activeModels ?? "—"}</strong></div><div className="stat"><span>purchases</span><strong>{analytics?.purchases ?? "—"}</strong></div></div><div className="grid gap-6"><section className="panel"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow">permissions</p><h2>Users and roles</h2></div><div className="flex gap-2"><button className="button button-soft" onClick={unpause}>Unpause</button><button className="button button-coral" onClick={pause}>Pause</button></div></div><div className="overflow-x-auto"><table className="admin-table"><thead><tr><th>Wallet</th><th>Username</th><th>Role</th><th>Joined</th></tr></thead><tbody>{users.map(item => <tr key={item.id}><td className="font-mono text-xs">{item.wallet_address.slice(0,10)}…{item.wallet_address.slice(-6)}</td><td>{item.username || "—"}</td><td><select className="mini-select" value={item.role} onChange={e => void changeRole(item.id, e.target.value)}><option value="customer">Customer</option><option value="creator">Creator</option><option value="support_admin">Support Admin</option><option value="moderator">Moderator</option><option value="super_admin">Super Admin</option></select></td><td className="text-xs text-slate-500">{new Date(item.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></section><section className="panel"><p className="eyebrow">moderation queue</p><h2 className="mb-5">Reported models</h2>{reports.length ? <div className="grid gap-3">{reports.map(report => <div key={report.id} className="rounded-xl bg-paper p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{report.title}</p><p className="mt-1 text-sm text-slate-500">{report.reason}</p></div><span className="status-badge">{report.status}</span></div></div>)}</div> : <div className="empty-state">No open reports. Nice work.</div>}</section>{message ? <p className="text-sm font-semibold text-violet">{message}</p> : null}</div></div></main>;
}
